---
version: "2"
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr:/config
      - ./sonarr/tv:/tv
      - ./sonarr/downloads:/downloads
    ports:
      - 8089:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr:/config
      - ./radarr/movies:/movies
      - ./radarr/movies/downloads:/downloads
    ports:
      - 8078:7878
    restart: unless-stopped
    